import type { MapPinSummary, PoliticianSummary, PollSummary } from "@/types";
import type { PinDetail } from "@/types/pin-detail";

export const DEMO_PINS: MapPinSummary[] = [
  {
    id: "demo-1",
    title: "Café Sol",
    description: "Solrik uteservering hele ettermiddagen.",
    latitude: 59.9225,
    longitude: 10.7525,
    address: "Thorvald Meyers gate 30",
    bydel: "GRUNERLOKKA",
    category: "SPISESTED",
    hashtags: ["#solservering", "#kafé"],
    contentCount: 2,
    reviewCount: 4,
    avgRating: 4.5,
  },
  {
    id: "demo-2",
    title: "Vulkan-huset",
    description: "Industrihistorie fra 1800-tallet, nå kulturhus.",
    latitude: 59.922,
    longitude: 10.751,
    address: "Vulkan 1",
    bydel: "GRUNERLOKKA",
    category: "BYGNING",
    hashtags: ["#lokalhistorie"],
    contentCount: 3,
    reviewCount: 1,
    avgRating: 5,
  },
  {
    id: "demo-3",
    title: "Aker Brygge terrasse",
    description: "Populært utested med utsikt mot fjorden.",
    latitude: 59.909,
    longitude: 10.726,
    address: "Aker Brygge",
    bydel: "FROGNER",
    category: "UTESTED",
    hashtags: ["#uteservering", "#utsikt"],
    contentCount: 1,
    reviewCount: 6,
    avgRating: 3.8,
  },
];

export const DEMO_PIN_DETAILS: Record<string, PinDetail> = {
  "demo-1": {
    id: "demo-1",
    title: "Café Sol",
    description: "Solrik uteservering hele ettermiddagen.",
    latitude: 59.9225,
    longitude: 10.7525,
    address: "Thorvald Meyers gate 30",
    bydel: "GRUNERLOKKA",
    category: "SPISESTED",
    terraceFacing: "SV",
    hashtags: ["#solservering", "#kafé"],
    contentCount: 2,
    reviewCount: 2,
    avgRating: 4.5,
    contents: [
      {
        id: "c1",
        type: "TEXT",
        textContent: "Beste solen på Løkka mellom 15–19 om våren. Terrassen vender sørvest.",
        mediaUrl: null,
        authorAlias: "LøkkaLokal",
        createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
      },
      {
        id: "c2",
        type: "TEXT",
        textContent: "Perfekt for kaffe og vafler en lørdagsettermiddag.",
        mediaUrl: null,
        authorAlias: null,
        createdAt: new Date(Date.now() - 86400000).toISOString(),
      },
    ],
    reviews: [
      {
        id: "r1",
        rating: 5,
        comment: "Fantastisk sol og god kaffe!",
        authorAlias: "Soljeger",
        createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
      },
      {
        id: "r2",
        rating: 4,
        comment: "Litt trangt, men verdt det for solen.",
        authorAlias: null,
        createdAt: new Date(Date.now() - 86400000).toISOString(),
      },
    ],
  },
  "demo-2": {
    id: "demo-2",
    title: "Vulkan-huset",
    description: "Industrihistorie fra 1800-tallet, nå kulturhus.",
    latitude: 59.922,
    longitude: 10.751,
    address: "Vulkan 1",
    bydel: "GRUNERLOKKA",
    category: "BYGNING",
    terraceFacing: null,
    hashtags: ["#lokalhistorie"],
    contentCount: 1,
    reviewCount: 1,
    avgRating: 5,
    contents: [
      {
        id: "c3",
        type: "TEXT",
        textContent:
          "Vulkan var et jernstøperi fra 1850-tallet. Bygget er bevart og brukes nå til kultur og mat.",
        mediaUrl: null,
        authorAlias: "Historikeren",
        createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
      },
    ],
    reviews: [
      {
        id: "r3",
        rating: 5,
        comment: "Fascinerende historie – verdt et besøk!",
        authorAlias: null,
        createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
      },
    ],
  },
  "demo-3": {
    id: "demo-3",
    title: "Aker Brygge terrasse",
    description: "Populært utested med utsikt mot fjorden.",
    latitude: 59.909,
    longitude: 10.726,
    address: "Aker Brygge",
    bydel: "FROGNER",
    category: "UTESTED",
    terraceFacing: "V",
    hashtags: ["#uteservering", "#utsikt"],
    contentCount: 0,
    reviewCount: 1,
    avgRating: 3.8,
    contents: [],
    reviews: [
      {
        id: "r4",
        rating: 4,
        comment: "Fin utsikt, men dyrt og travelt.",
        authorAlias: "Osloveien",
        createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
      },
    ],
  },
};

export const DEMO_POLITICIANS: PoliticianSummary[] = [
  {
    id: "demo-p1",
    name: "Anne Beate Hjernø",
    party: "Arbeiderpartiet",
    role: "Byråd for byutvikling",
    bydel: null,
    avgRating: 3.9,
    feedbackCount: 12,
  },
  {
    id: "demo-p2",
    name: "Eirik Lae Solberg",
    party: "Høyre",
    role: "Byrådsleder",
    bydel: null,
    avgRating: 3.2,
    feedbackCount: 28,
  },
  {
    id: "demo-p3",
    name: "Rasmus Reinvang",
    party: "MDG",
    role: "Byråd for miljø og transport",
    bydel: null,
    avgRating: 4.1,
    feedbackCount: 19,
  },
];

export const DEMO_POLLS: PollSummary[] = [
  {
    id: "demo-poll-1",
    question: "Bør det bygges flere sykkelfelt i sentrum?",
    description: "Stem på hva du mener er viktigst for hverdagen i Oslo sentrum.",
    bydel: "GAMLE_OSLO",
    createdAt: new Date().toISOString(),
    totalVotes: 142,
    options: [
      { id: "o1", label: "Ja, prioritér sykkel", votes: 89, percentage: 63 },
      { id: "o2", label: "Nei, behold biltrafikk", votes: 18, percentage: 13 },
      { id: "o3", label: "Kombinert løsning", votes: 35, percentage: 25 },
    ],
    politicians: [{ id: "demo-p3", name: "Rasmus Reinvang", party: "MDG" }],
  },
  {
    id: "demo-poll-2",
    question: "Trenger Grünerløkka flere grønne plasser?",
    description: null,
    bydel: "GRUNERLOKKA",
    createdAt: new Date().toISOString(),
    totalVotes: 67,
    options: [
      { id: "o4", label: "Ja", votes: 52, percentage: 78 },
      { id: "o5", label: "Nei", votes: 15, percentage: 22 },
    ],
    politicians: [],
  },
];
